### ISSUE TITLE
trim on page edges

### ISSUE THREAD

**Issue by haschdl** [LoicGoulefert/occult#19]
Hello, I came to your library from the mention in https://github.com/evil-mad/axidraw/issues/100
Is there a combination of arguments that would simply trim the excess paths that go over a page?
(Context: creating the SVG from Processing will generate SVG files with paths that go beyond the page border)

**Comment by LoicGoulefert** [comment]
Hi ! I don't think `occult` is required for this task, vpype [crop](https://vpype.readthedocs.io/en/latest/reference.html#crop) command should do the trick.
