### ISSUE TITLE
Idea: Option to ignore ' fill="none" ' geometries

### ISSUE THREAD

**Issue by lewi0622** [LoicGoulefert/occult#21]
It would be nice to have an additional argument to ignore geometries that have fill set to none or are else transparent in the SVG.

**Comment by LoicGoulefert** [comment]
Hey @lewi0622 ! I'll have to take a look at vpype to see if we can achieve this here, before trying to add it to occult.

**Comment by LoicGoulefert** [comment]
You could do something like this : 

- Group attributes by fill property :  `vpype read  --attr fill input.svg  show` 
- Find which layer contains the 'fill=none' property
- Perform occlusion on every other layers : `vpype read  --attr fill input.svg occult -l 1 show` (to be modified accordingly)

Tell me if this works for you !
