### ISSUE TITLE
ShapelyDeprecationWarning: STRtree will be changed in 2.0.0 and will not be compatible with versions < 2.

### ISSUE THREAD

**Issue by vmario89** [LoicGoulefert/occult#22]
Hi, this warning occures to me when running

```
/home/himbeere/.local/lib/python3.10/site-packages/occult/occult.py:52: ShapelyDeprecationWarning: STRtree will be changed in 2.0.0 and will not be compatible with versions < 2.
  tree = STRtree(line_arr_lines)
```

**Comment by LoicGoulefert** [comment]
Hi @vmario89 ! For now, this deprecation warning occurs if you're running Shapely > 1.8.2 ([Release notes for 1.8.3](https://github.com/shapely/shapely/releases/tag/1.8.3). I couldn't find instructions as to how to upgrade to avoid this warning, so I'll be waiting until Shapely 2.0 is out of alpha to fix this. Thanks for the heads up !

**Comment by LoicGoulefert** [comment]
With occult [0.4.0 release](https://github.com/LoicGoulefert/occult/releases/tag/0.4.0), you can update shapely to version 2.0.0. Deprecation warnings gone, and a slight speedup are expected !
