### ISSUE TITLE
Does not run on Windows 10 with Python 3.9

### ISSUE THREAD

**Issue by vmario89** [LoicGoulefert/occult#5]
Hi,

trying to execute occult on Windows 10 but it does not work for me. I installed vpype using pip3 (Python3.9) ```pip install vpype``` and then ```pip install git+https://github.com/abey79/occult.git#egg=occult```

installation works without errros. vpype executes without any hassle. But as soon as applying "occult" command to vpype it fails:

```
C:\Users\tomate\Downloads>vpype read drawing.svg occult

Warning: entry point could not be loaded. Contact its author for help.


Traceback (most recent call last):
  File "c:\users\tomate\appdata\local\programs\python\python39\lib\site-packages\click_plugins\core.py", line 37, in decorator
    group.add_command(entry_point.load())
  File "c:\users\tomate\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "c:\users\tomate\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\tomate\appdata\local\programs\python\python39\lib\site-packages\occult\occult.py", line 7, in <module>
    import pygeos
  File "c:\users\tomate\appdata\local\programs\python\python39\lib\site-packages\pygeos\__init__.py", line 1, in <module>
    from .lib import GEOSException  # NOQA
ImportError: DLL load failed while importing lib: Die angegebene Prozedur wurde nicht gefunden.
```

could it be missing GEOS bindings? i checked https://www.gisinternals.com/query.html?content=filelist&file=release-1900-gdal-3-0-2-mapserver-7-4-2.zip and i cannot find sth for Python 3.9. At least some help about external requirements or python version would be helpful.

thanks for your work and time :-)

**Comment by vmario89** [comment]
some info: tried the same version of vpype and occult on Ubuntu 20, using Python 3.8.5 - this works fine. after trying Python 3.8 i trief Python3.9 on Ubuntu 20 LTS and it failed to install vpype and it killed my terminal (made it disappearing).

**Comment by vmario89** [comment]
Hey,
found a way to fix this. the error is dropped by pygeos. The following procedure helps:

1. Install OSGeo4W
    - Download and install GEOS library/binaries. You can get this from https://trac.osgeo.org/osgeo4w
    - Direct URL to download x64 setup: http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe

2. Set environment variables for GEOS
   - GEOS_INCLUDE_PATH = C:\OSGeo4W64\include
   - GEOS_LIBRARY_PATH = C:\OSGeo4W64\lib

3. Install Visual Studio Community Edition 2017 or newer
   - We need VS to compile pygeos. Downloadable at https://visualstudio.microsoft.com/de/downloads

4. pip3 install pygeos --force-reinstall --no-binary pygeos

![grafik](https://user-images.githubusercontent.com/5631071/113442787-fc582000-93f0-11eb-9030-a15e73a098a2.png)

**Comment by LoicGoulefert** [comment]
Hi Mario !

Glad you found a workaround. @abey79 also encountered this problem (https://github.com/pygeos/pygeos/issues/311). 
I rewrote the plugin using `shapely.strtree` instead of pygeos' STRTree, hopefully this will allow Windows users to run it without issues !

**Comment by vmario89** [comment]
cool this is nice. i deleted pygeos library from system and cleaned system paths from the 2 required system env strings; updated to your latest commit and it still works. so it should be fine!
