### ISSUE TITLE
Integration in InkScape

### ISSUE THREAD

**Issue by vmario89** [LoicGoulefert/occult#6]
Hi,
wanted to let you know i implemented occult as InkScape extension! :-)

https://stadtfabrikanten.org/pages/viewpage.action?pageId=103612550
https://gitea.fablabchemnitz.de/MarioVoigt/mightyscape-1.X/src/branch/master/extensions/fablabchemnitz/vpypetools

**Comment by LoicGoulefert** [comment]
Hi Mario,

Great job ! Thank you for doing this ! :)

**Comment by vmario89** [comment]
thanks for integrating the -k parameter. Really cool. I updated InkScape extension/docs accordingly :-)
