### ISSUE TITLE
Occult does not apply for some graphics

### ISSUE THREAD

**Issue by vmario89** [LoicGoulefert/occult#7]
Hi,
sometimes occult does nothing on a SVG file. I attached a cardbox (https://sourceforge.net/p/razorfoss/svn/HEAD/tree/trunk/Inkscape/TuckboxExtension/) which has multiple lines over each other but they still exist after running occult. Do you have an idea what could be the reason?

i already checked if all points are snapped to each other. I played with different tolerance values from tiny to large. no difference.

before running occult i have 28 elements
![grafik](https://user-images.githubusercontent.com/5631071/114692667-1b23b400-9d19-11eb-8c26-8bd349305b12.png)

after running occult i have 30 elements
![grafik](https://user-images.githubusercontent.com/5631071/114692768-34c4fb80-9d19-11eb-9408-87a5cbdc29fc.png)

i attached the sample file here:
[drawing.zip](https://github.com/LoicGoulefert/occult/files/6310018/drawing.zip)

regards, Mario

**Comment by LoicGoulefert** [comment]
Hi Mario !

The purpose of occult is to remove lines, or part of lines that are hidden by a polygon. I'm afraid that this plugin is not suited for removing overlapping lines. Maybe at some point I'll add an option to allow occult to do this, or maybe create another plugin dedicated to this task.

I'll update the README to clarify this !

**Comment by vmario89** [comment]
Hey, thanks for clarifying. 

btw. do you think you could add a plugin option parameter to allow saving occulted lines in a separate layer instead removing them?

Having a plugin to remove common lines would be great. I never found any python routine which could do that. occult comes really near.

regards, Mario :-)

**Comment by LoicGoulefert** [comment]
Regarding the option to save occulted lines in a separate layer, this would be doable and would be a great addition to this plugin, I'll implement it soon !

A plugin to remove overlapping lines would be great too, but I'm not sure when I'll be able to implement it. I'll keep you updated on this :)

**Comment by LoicGoulefert** [comment]
@vmario89 I've merged the feature to keep occulted lines in a separate layer :)

**Comment by vmario89** [comment]
> A plugin to remove overlapping lines would be great too, but I'm not sure when I'll be able to implement it. I'll keep you updated on this :)

i am trying to do such a tool chain with shapely at the moment. Its not so easy to do i think but i think we could do the following approach using vpype and/or inkscape together:

- get all lines as collection into shapely (vpype)
- find all intersection points of all lines. Add those points to an array if not present in that array yet (no duplicate intersection points)
- split up each line with those intersection points. we need to check if the intersection point is on the line. So that would be the case if the distance from the intersection point is realy really small (effectively zero) and if this point is between starting point and end point
- put all those split up segments to a new array and filter it for duplicate lines (same start and end point); or: combine all those lines to a merged one and run https://stadtfabrikanten.org/display/IFM/Purge+Duplicate+Path+Segments
- 
regards, Mario

**Comment by LoicGoulefert** [comment]
Hi Mario, sorry for the delay.
I made a vpype [plugin](https://github.com/LoicGoulefert/deduplicate) to deduplicate lines in a SVG file. It currently has a few edge cases where de-duplication doesn't work. Hopefully it can be useful to you !

**Comment by vmario89** [comment]
cool. thanks for notifying me. i am going to try this out asap =)
